version: "3.3"

services:
  cicd-nginx:
    image: 'nginx:stable-alpine'
    container_name: cicd-nginx
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  cicd-app:
    build: 
      context: .
      dockerfile: app.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: cicd-app
    volumes:
      - ./:/var/www/html