name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "Login to the docker registry"

          docker pull ghcr.io/chethanakh/cicd_with_docker/app:$GITHUB_REF_NAME && echo "$GITHUB_REF_NAME already exists!" && exit 1 || echo "Building $GITHUB_REF_NAME..."

          docker-compose -f docker-compose.prod.yaml build

          docker tag cicd-app-prod:hot ghcr.io/chethanakh/cicd_with_docker/app:hot

          docker push ghcr.io/chethanakh/cicd_with_docker/app:hot


     - run: echo "build success"
